package fournf

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"entgo.io/ent/entc/gen"
)

// classDiagram is the gen.Hook behind [WithClassDiagram]. It runs after code
// generation so a failed build never leaves a diagram behind.
func (e *Extension) classDiagram(next gen.Generator) gen.Generator {
	return gen.GenerateFunc(func(g *gen.Graph) error {
		if err := next.Generate(g); err != nil {
			return err
		}
		if dir := filepath.Dir(e.classDiagramPath); dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return fmt.Errorf("creating directory for class diagram: %w", err)
			}
		}
		if err := os.WriteFile(e.classDiagramPath, []byte(renderClassDiagram(g)), 0o644); err != nil {
			return fmt.Errorf("writing class diagram: %w", err)
		}
		return nil
	})
}

// association is one relationship line in the diagram.
type association struct {
	from, to string
	fromCard string
	toCard   string
	label    string
}

// renderClassDiagram returns the Mermaid class diagram for the graph. Join
// tables collapse into association lines between the entities they connect, so
// the diagram shows the domain rather than the storage.
func renderClassDiagram(g *gen.Graph) string {
	var (
		entities []*gen.Type
		joins    []*gen.Type
	)
	for _, n := range g.Nodes {
		if isJoinTable(n) && len(fkEdges(n)) == 2 {
			joins = append(joins, n)
			continue
		}
		// A join table that does not connect exactly two entities is drawn as
		// a class: there is no single association it could collapse into.
		entities = append(entities, n)
	}
	sort.Slice(entities, func(i, j int) bool { return entities[i].Name < entities[j].Name })
	sort.Slice(joins, func(i, j int) bool { return joins[i].Name < joins[j].Name })

	var b strings.Builder
	b.WriteString("%% Code generated by fournf. DO NOT EDIT.\n")
	b.WriteString("%% Join tables are collapsed into associations; multiplicity comes from their unique indexes.\n")
	b.WriteString("classDiagram\n")
	for _, n := range entities {
		writeClass(&b, n)
	}

	assocs := joinAssociations(joins)
	assocs = append(assocs, wideJoinAssociations(entities)...)
	assocs = append(assocs, directAssociations(entities)...)
	sort.Slice(assocs, func(i, j int) bool {
		if assocs[i].from != assocs[j].from {
			return assocs[i].from < assocs[j].from
		}
		if assocs[i].label != assocs[j].label {
			return assocs[i].label < assocs[j].label
		}
		return assocs[i].to < assocs[j].to
	})
	for _, a := range assocs {
		fmt.Fprintf(&b, "    %s %q -- %q %s : %s\n", a.from, a.fromCard, a.toCard, a.to, a.label)
	}
	return b.String()
}

// writeClass writes one class block: the ID field followed by every non-edge
// field, each as "+<go type> <name>".
func writeClass(b *strings.Builder, n *gen.Type) {
	fmt.Fprintf(b, "    class %s {\n", n.Name)
	if n.HasOneFieldID() {
		fmt.Fprintf(b, "        +%s %s\n", fieldType(n.ID), n.ID.Name)
	}
	for _, f := range n.Fields {
		if f.IsEdgeField() {
			continue
		}
		fmt.Fprintf(b, "        +%s %s\n", fieldType(f), f.Name)
	}
	b.WriteString("    }\n")
}

// joinAssociations turns each join table into one association between the two
// entities it connects.
func joinAssociations(joins []*gen.Type) []association {
	out := make([]association, 0, len(joins))
	for _, j := range joins {
		edges := fkEdges(j)
		a, z := edges[0], edges[1]
		out = append(out, association{
			from:     a.Type.Name,
			to:       z.Type.Name,
			fromCard: cardinality(j, z.Field().Name),
			toCard:   cardinality(j, a.Field().Name),
			label:    j.Name,
		})
	}
	return out
}

// wideJoinAssociations links a join table that was not collapsed, because it
// connects other than two entities, to each entity it references. Every row of
// such a join points at exactly one of each.
func wideJoinAssociations(entities []*gen.Type) []association {
	var out []association
	for _, n := range entities {
		if !isJoinTable(n) {
			continue
		}
		for _, e := range fkEdges(n) {
			out = append(out, association{
				from:     n.Name,
				to:       e.Type.Name,
				fromCard: cardinality(n, e.Field().Name),
				toCard:   "1",
				label:    e.Name,
			})
		}
	}
	return out
}

// cardinality reports the multiplicity to show on the side opposite fk. A
// unique index on fk means that entity appears in the join at most once, so
// exactly one row relates to it; without one it may appear any number of times.
func cardinality(j *gen.Type, fk string) string {
	for _, ix := range j.Indexes {
		if ix.Unique && len(ix.Columns) == 1 && ix.Columns[0] == fk {
			return "1"
		}
	}
	return "0..*"
}

// directAssociations covers entity-to-entity edges, which fournf permits as
// long as they carry no foreign key field. A bidirectional edge is drawn from
// its owning side only, so it appears once.
func directAssociations(entities []*gen.Type) []association {
	var out []association
	for _, n := range entities {
		for _, e := range n.Edges {
			if e.IsInverse() || isJoinTable(e.Type) || e.Field() != nil {
				continue
			}
			// The near side's multiplicity is only known when an inverse edge
			// declares it.
			near := "0..*"
			if e.Ref != nil {
				near = edgeCardinality(e.Ref)
			}
			out = append(out, association{
				from:     n.Name,
				to:       e.Type.Name,
				fromCard: near,
				toCard:   edgeCardinality(e),
				label:    e.Name,
			})
		}
	}
	return out
}

func edgeCardinality(e *gen.Edge) string {
	switch {
	case e.Unique && e.Optional:
		return "0..1"
	case e.Unique:
		return "1"
	default:
		return "0..*"
	}
}

// fkEdges returns the edges of n that carry a foreign key field.
func fkEdges(n *gen.Type) []*gen.Edge {
	var out []*gen.Edge
	for _, e := range n.Edges {
		if e.Field() != nil {
			out = append(out, e)
		}
	}
	return out
}

// fieldType renders a field's Go type for a class attribute. Mermaid treats a
// comma as an attribute separator, so map and composite types are simplified.
func fieldType(f *gen.Field) string {
	t := f.Type.String()
	if i := strings.IndexAny(t, ",<{"); i >= 0 {
		t = t[:i]
	}
	return strings.TrimSpace(t)
}
