package fournf

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
)

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

// testGraph loads internal/testschema, a small 4NF schema covering one join of
// each multiplicity, a join across three entities, and an edge with no
// foreign key.
func testGraph(t *testing.T) *gen.Graph {
	t.Helper()
	g, err := entc.LoadGraph("./internal/testschema", &gen.Config{
		Package: "github.com/blobmasterbrian/fournf/internal/testschema/gen",
	})
	if err != nil {
		t.Fatalf("loading test schema: %v", err)
	}
	return g
}

// ---------------------------------------------------------------------------
// TestWithClassDiagram
// ---------------------------------------------------------------------------

func TestWithClassDiagram(t *testing.T) {
	t.Run("not set", func(t *testing.T) {
		ext, err := NewExtension()
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if ext.classDiagramPath != "" {
			t.Errorf("classDiagramPath = %q, want empty", ext.classDiagramPath)
		}
		if got := len(ext.Hooks()); got != 1 {
			t.Errorf("len(Hooks()) = %d, want 1", got)
		}
	})
	t.Run("set", func(t *testing.T) {
		ext, err := NewExtension(WithClassDiagram("schema.mmd"))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if ext.classDiagramPath != "schema.mmd" {
			t.Errorf("classDiagramPath = %q, want %q", ext.classDiagramPath, "schema.mmd")
		}
		if got := len(ext.Hooks()); got != 2 {
			t.Errorf("len(Hooks()) = %d, want 2", got)
		}
	})
}

// ---------------------------------------------------------------------------
// TestRenderClassDiagram
// ---------------------------------------------------------------------------

func TestRenderClassDiagram(t *testing.T) {
	out := renderClassDiagram(testGraph(t))

	t.Run("header", func(t *testing.T) {
		if !strings.HasPrefix(out, "%% Code generated by fournf. DO NOT EDIT.\n") {
			t.Error("diagram does not start with the generated-code marker")
		}
		if !strings.Contains(out, "\nclassDiagram\n") {
			t.Error("diagram has no classDiagram declaration")
		}
	})

	t.Run("entity classes", func(t *testing.T) {
		for _, want := range []string{"Article", "Profile", "Session", "Tag", "User"} {
			if !strings.Contains(out, "    class "+want+" {\n") {
				t.Errorf("no class block for entity %q", want)
			}
		}
	})

	t.Run("collapsed joins are not classes", func(t *testing.T) {
		for _, join := range []string{"UserProfile", "UserSession", "ArticleTag"} {
			if strings.Contains(out, "    class "+join+" {\n") {
				t.Errorf("join table %q was drawn as a class instead of an association", join)
			}
		}
	})

	t.Run("fields", func(t *testing.T) {
		for _, want := range []string{"+uuid.UUID id", "+string name", "+time.Time created_at"} {
			if !strings.Contains(out, want) {
				t.Errorf("missing field line %q", want)
			}
		}
	})

	t.Run("foreign keys are not fields", func(t *testing.T) {
		for _, fk := range []string{"user_id", "profile_id", "article_id"} {
			if strings.Contains(out, " "+fk+"\n") {
				t.Errorf("foreign key %q was drawn as a class attribute", fk)
			}
		}
	})

	t.Run("associations", func(t *testing.T) {
		tests := []struct{ name, want string }{
			{"one to one", `User "1" -- "1" Profile : UserProfile`},
			{"one to many", `User "1" -- "0..*" Session : UserSession`},
			{"many to many", `Article "0..*" -- "0..*" Tag : ArticleTag`},
			{"edge without a foreign key", `User "0..*" -- "0..*" Article : favorites`},
			{"three-way join keeps its class", `ArticleTagUser "0..*" -- "1" Article : article`},
		}
		for _, tt := range tests {
			t.Run(tt.name, func(t *testing.T) {
				if !strings.Contains(out, "    "+tt.want+"\n") {
					t.Errorf("missing association %q", tt.want)
				}
			})
		}
	})

	t.Run("bidirectional edge drawn once", func(t *testing.T) {
		if strings.Contains(out, ": fans") {
			t.Error("inverse edge was drawn in addition to its owning side")
		}
	})

	t.Run("stable output", func(t *testing.T) {
		if again := renderClassDiagram(testGraph(t)); again != out {
			t.Error("rendering the same graph twice produced different output")
		}
	})
}

// ---------------------------------------------------------------------------
// TestClassDiagramHook
// ---------------------------------------------------------------------------

func TestClassDiagramHook(t *testing.T) {
	t.Run("writes the file and creates parent directories", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "docs", "schema.mmd")
		ext, err := NewExtension(WithClassDiagram(path))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		next, called := noopGenerator()
		if err := ext.classDiagram(next).Generate(testGraph(t)); err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !*called {
			t.Error("the next generator was not called")
		}
		b, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("reading diagram: %v", err)
		}
		if !strings.Contains(string(b), "classDiagram") {
			t.Error("written file is not a class diagram")
		}
	})

	t.Run("nothing is written when generation fails", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "schema.mmd")
		ext, err := NewExtension(WithClassDiagram(path))
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		sentinel := errors.New("generate failed")
		next := gen.GenerateFunc(func(*gen.Graph) error { return sentinel })
		if err := ext.classDiagram(next).Generate(testGraph(t)); !errors.Is(err, sentinel) {
			t.Fatalf("error = %v, want %v", err, sentinel)
		}
		if _, err := os.Stat(path); !os.IsNotExist(err) {
			t.Error("a diagram was written even though generation failed")
		}
	})
}

// ---------------------------------------------------------------------------
// TestCardinality
// ---------------------------------------------------------------------------

func TestCardinality(t *testing.T) {
	j := &gen.Type{
		Name: "UserSession",
		Indexes: []*gen.Index{
			{Columns: []string{"user_id"}},
			{Columns: []string{"session_id"}, Unique: true},
			{Columns: []string{"user_id", "session_id"}, Unique: true},
		},
	}
	tests := []struct{ name, fk, want string }{
		{"unique single column", "session_id", "1"},
		{"non-unique single column", "user_id", "0..*"},
		{"absent", "other_id", "0..*"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := cardinality(j, tt.fk); got != tt.want {
				t.Fatalf("cardinality(%q) = %q, want %q", tt.fk, got, tt.want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// TestFieldType
// ---------------------------------------------------------------------------

func TestFieldType(t *testing.T) {
	// A composite type would introduce a comma, which Mermaid reads as an
	// attribute separator.
	tests := []struct{ in, want string }{
		{"uuid.UUID", "uuid.UUID"},
		{"time.Time", "time.Time"},
		{"map[string]int", "map[string]int"},
		{"func(int, int)", "func(int"},
	}
	for _, tt := range tests {
		t.Run(tt.in, func(t *testing.T) {
			f := &gen.Field{Type: &field.TypeInfo{Ident: tt.in}}
			if got := fieldType(f); got != tt.want {
				t.Fatalf("fieldType(%q) = %q, want %q", tt.in, got, tt.want)
			}
		})
	}
}
